//-----------------------------------------------------------------------
// <copyright file="EditorAppConfigFileBuidler.cs" company="DefaultCompany">
//     Copyright (c) DefaultCompany. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Lost.AppConfig
{
    using System.Collections.Generic;
    using System.IO;
    using System.Text;
    using UnityEditor;
    using UnityEditor.VersionControl;

    public static class EditorAppConfigFileBuidler
    {
        [MenuItem("Lost/Generate AppConfigs C# File")]
        private static void GenerateAppConfigsFile()
        {
            StringBuilder file = new StringBuilder();
            file.AppendLine("// <auto-generated/>              ".TrimEnd());
            file.AppendLine("#pragma warning disable           ".TrimEnd());
            file.AppendLine("                                  ".TrimEnd());
            file.AppendLine("using Lost.AppConfig;             ".TrimEnd());
            file.AppendLine("using UnityEditor;                ".TrimEnd());
            file.AppendLine("                                  ".TrimEnd());
            file.AppendLine("public static class AppConfigs    ".TrimEnd());
            file.AppendLine("{                                 ".TrimEnd());
            file.Append(GetConstants());
            file.Append(GetMethods());
            file.AppendLine("}");

            // Writing out to disk and refershing
            string path = EditorAppConfig.AppConfigScriptPath;

            if (File.Exists(path) && Provider.isActive)
            {
                var asset = AssetDatabase.LoadAllAssetsAtPath(path);
                Provider.Checkout(asset, CheckoutMode.Asset).Wait();
            }

            File.WriteAllText(path, file.ToString());
            AssetDatabase.ImportAsset(path);
            AssetDatabase.Refresh();
        }

        private static string GetConstants()
        {
            StringBuilder constants = new StringBuilder();

            foreach (var appConfig in EditorAppConfig.AppConfigs)
            {
                // If we have more than one config, then skip the root config
                if (EditorAppConfig.AppConfigs.Count > 1 && appConfig == EditorAppConfig.RootAppConfig)
                {
                    continue;
                }

                StringBuilder constantsBuilder = new StringBuilder();
                constantsBuilder.AppendLine("    private const string Config{config_name}Path = \"{menu_item_name}\";");
                constantsBuilder.AppendLine("    private const string Config{config_name}Guid = \"{config_guid}\";");

                string constantsString = constantsBuilder.ToString()
                    .Replace("{config_name}", appConfig.SafeName)
                    .Replace("{config_guid}", AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(appConfig.GetInstanceID())))
                    .Replace("{menu_item_name}", GetMenuItemName(appConfig));

                constants.AppendLine(constantsString);
            }

            return constants.ToString();
        }

        private static string GetMethods()
        {
            List<string> methods = new List<string>();

            foreach (var appConfig in EditorAppConfig.AppConfigs)
            {
                // If we have more than one config, then skip the root config
                if (EditorAppConfig.AppConfigs.Count > 1 && appConfig == EditorAppConfig.RootAppConfig)
                {
                    continue;
                }

                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("    [MenuItem(Config{config_name}Path, false)]                                                              ".TrimEnd());
                methodBuilder.AppendLine("    public static void Set{config_name}Config()                                                             ".TrimEnd());
                methodBuilder.AppendLine("    {                                                                                                       ".TrimEnd());
                methodBuilder.AppendLine("        EditorAppConfig.SetActiveConfig(Config{config_name}Guid);                                           ".TrimEnd());
                methodBuilder.AppendLine("    }                                                                                                       ".TrimEnd());
                methodBuilder.AppendLine("                                                                                                            ".TrimEnd());
                methodBuilder.AppendLine("    [MenuItem(Config{config_name}Path, true)]                                                               ".TrimEnd());
                methodBuilder.AppendLine("    private static bool Set{config_name}ConfigValidate()                                                    ".TrimEnd());
                methodBuilder.AppendLine("    {                                                                                                       ".TrimEnd());
                methodBuilder.AppendLine("        Menu.SetChecked(Config{config_name}Path, EditorAppConfig.IsActiveConfig(Config{config_name}Guid));  ".TrimEnd());
                methodBuilder.AppendLine("        return true;                                                                                        ".TrimEnd());
                methodBuilder.AppendLine("    }                                                                                                       ".TrimEnd());

                methods.Add(methodBuilder.ToString().Replace("{config_name}", appConfig.SafeName));
            }

            // Constructing the final methods string
            StringBuilder methodsBuilder = new StringBuilder();

            for (int i = 0; i < methods.Count; i++)
            {
                if (i != methods.Count -1)
                {
                    methodsBuilder.AppendLine(methods[i]);
                }
                else
                {
                    methodsBuilder.Append(methods[i]);
                }
            }

            return methodsBuilder.ToString();
        }

        private static string GetSafeAppConfigName(AppConfig appConfig)
        {
            return appConfig.Parent != null ?
                   GetSafeAppConfigName(appConfig.Parent) + "/" + appConfig.SafeName :
                   appConfig.SafeName;
        }

        private static string GetMenuItemName(AppConfig appConfig)
        {
            string menuItemName = "Lost/Configs/" + GetSafeAppConfigName(appConfig);

            // Removing the root config from the menu item path if we have more than one configs
            if (EditorAppConfig.AppConfigs.Count > 1)
            {
                menuItemName = menuItemName.Replace(EditorAppConfig.RootAppConfig.SafeName + "/", string.Empty);
            }

            return menuItemName;
        }
    }
}
